<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario->nome ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br>
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets->total_tweet ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br>
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo->total_seguindo ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br>
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores->total_seguidores ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form id="form_procurar_pessoas">
								<div class="input-group mb-3">
									<input type="text" id="txt_nome" name="pesquisar_por" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" id="btn_pesquisar" type="submit">
											Procurar
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<div id="pessoas"></div>

		</div>
	</div>
</div>